version: '3.8'

services:
  worker-1:
    build: .
    container_name: worker-1
    hostname: worker-1
    networks:
      - mapreduce-net

  coordinator:
    build: .
    container_name: coordinator
    hostname: coordinator
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./txt:/app/txt
      - ./coordinator.py:/app/coordinator.py
    command: python -u coordinator.py
    depends_on:
      - worker-1
    networks:
      - mapreduce-net

networks:
  mapreduce-net:
    driver: bridge