version: '3.8'

services:
  worker-1:
    build: .
    container_name: worker-1
    hostname: worker-1
    networks:
      - mapreduce-net

  worker-2:
    build: .
    container_name: worker-2
    hostname: worker-2
    networks:
      - mapreduce-net

  coordinator:
    build: .
    container_name: coordinator
    hostname: coordinator
    volumes:
      - ./txt:/app/txt
      - ./coordinator.py:/app/coordinator.py
    command: python coordinator.py
    depends_on:
      - worker-1
      - worker-2
    networks:
      - mapreduce-net

networks:
  mapreduce-net:
    driver: bridge